version: "3.8"

services:
  crypto_ai_bot:
    image: crypto_ai_bot_main
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml
    restart: always
